/**
 * Api error codes sent by the Paylike backend
 */
public enum ApiCodes : String, Decodable {
    case ENDPOINT_NOT_FOUND
    case INTERNAL_ERROR
    case VERSION_MISSING
    case VERSION_UNSUPPORTED
    case BODY_INVALID
    case REQUEST_INVALID
    case TOKEN_INVALID
    case TOKEN_TYPE_UNEXPECTED
    case TEST_MODE_MIXED
    case PAYMENT_INTEGRATION_KEY_UNKNOWN
    case PAYMENT_INTEGRATION_DISABLED
    case PAYMENT_CHALLENGE_UNAVAILABLE
    case PAYMENT_CARD_NUMBER_INVALID
    case PAYMENT_CARD_SCHEME_UNKNOWN
    case PAYMENT_CARD_SCHEME_UNSUPPORTED
    case PAYMENT_CARD_SECURITY_CODE_INVALID
    case PAYMENT_CARD_EXPIRED
    case PAYMENT_CARD_DISABLED
    case PAYMENT_CARD_LOST
    case PAYMENT_AMOUNT_LIMIT
    case PAYMENT_INSUFFICIENT_FUNDS
    case PAYMENT_RECEIVER_BLOCKED
    case PAYMENT_REJECTED_BY_ISSUER
    case PAYMENT_REJECTED
    case PAYMENT_METHOD_ERROR
    case TDSECURE_REQUIRED
    case TDSECURE_FAILED
    case TDSECURE_PARES_INVALID
    case PAYMENT_APPLEPAY_EXPIRED
}
