/**
 * HTTP Server status codes
 *
 * These error codes are sent by the Paylike backend server
 *
 * [More info](https://github.com/paylike/api-reference/blob/main/status-codes.md)
 */
public enum PaylikeErrorCodes : String, Decodable {
    case APPLEPAY_TOKEN_INVALID
    case APPLEPAY_VALIDATION_URL_INVALID
    case APPLEPAY_CONFIGURATION_INVALID
    case BODY_INVALID
    case ENDPOINT_NOT_FOUND
    case INTERNAL_ERROR
    case PAYMENT_AMOUNT_LIMIT
    case PAYMENT_APPLEPAY_AMOUNT_MISMATCH
    case PAYMENT_APPLEPAY_EXPIRED
    case PAYMENT_CARD_DISABLED
    case PAYMENT_CARD_EXPIRED
    case PAYMENT_CARD_SCHEME_UNKNOWN
    case PAYMENT_CARD_SCHEME_UNSUPPORTED
    case PAYMENT_CARD_SECURITY_CODE_INVALID
    case PAYMENT_CARD_LOST
    case PAYMENT_CARD_NUMBER_INVALID
    case PAYMENT_CHALLENGE_UNAVAILABLE
    case PAYMENT_INTEGRATION_DISABLED
    case PAYMENT_INTEGRATION_KEY_UNKNOWN
    case PAYMENT_INSUFFICIENT_FUNDS
    case PAYMENT_METHOD_ERROR
    case PAYMENT_RECEIVER_BLOCKED
    case PAYMENT_REJECTED
    case PAYMENT_REJECTED_BY_ISSUER
    case REQUEST_INVALID
    case TEST_MODE_MIXED
    case TDSECURE_FAILED
    case TDSECURE_PARES_INVALID
    case TDSECURE_REQUIRED
    case TOKEN_INVALID
    case TOKEN_TYPE_UNEXPECTED
    case VERSION_MISSING
    case VERSION_UNSUPPORTED
}
